# Generated by Django 4.0.2 on 2022-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
