# Generated by Django 4.0.2 on 2022-04-25 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_product_in_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
